# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
