# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configtables', '0001_initial'),
        ('clubs', '0002_auto_20171104_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='configtables.Region'),
        ),
    ]
